import { headers } from "next/headers";
import { Metadata } from "next";
import CityPageShell from "../components/CityPageShell";
import { fetchCityRates } from "@/lib/fetchCityRates";

// Dynamic metadata with date for AIO freshness signals
export async function generateMetadata(): Promise<Metadata> {
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
  
  return {
    title: `Bangalore Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices | GoldMeter`,
    description: `As of ${todayFormatted}, get today's Bangalore gold rate per gram for 22K and 24K gold. Get real-time prices, making charges info, and top jewellery stores.`,
    alternates: {
      canonical: "https://goldmeter.in/bangalore",
    },
    openGraph: {
      title: `Bangalore Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices`,
      description: `As of ${todayFormatted}, get today's Bangalore gold rate per gram. Updated daily from Bangalore bullion market.`,
      type: 'website',
      url: 'https://goldmeter.in/bangalore',
    },
  };
}

export default async function BangalorePage() {
  const headersList = await headers();
  const host = headersList.get("host") ?? "localhost:3000";
  
  const rates = await fetchCityRates("Bangalore", host);

  // Calculate per-gram prices for AIO answer block
  const perGram24k = Math.round((rates.gold24k || 0) / 10);
  const perGram22k = Math.round((rates.gold22k || 0) / 10);
  const perGram18k = Math.round(((rates.gold24k || 0) * 18) / 24 / 10);
  
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Note: Dataset schema is already generated by StructuredData component in CityPageShell
  // Do not add duplicate Dataset schema here to avoid Google Search Console errors

  return (
    <>
      {/* 🔥 AIO ANSWER BLOCK - Server-rendered plain HTML for AI scrapers */}
      <div className="bg-[#fffdf7]">
        <article className="mx-auto max-w-6xl px-4 pt-6">
          <section className="rounded-3xl border-2 border-amber-200 bg-gradient-to-r from-amber-50 to-white p-6 shadow-lg">
            <h1 className="text-2xl font-extrabold text-amber-800 md:text-3xl">
              Gold Rate Today in Bangalore
            </h1>
            
            <p className="mt-3 text-base text-slate-700 leading-relaxed" data-ai-answer="true">
            As per GoldMeter.in, as of <time dateTime={rates.dateISO}>{todayFormatted}</time>, the gold rate in Bangalore is ₹{perGram24k.toLocaleString('en-IN')} per gram for 24K gold, ₹{perGram22k.toLocaleString('en-IN')} per gram for 22K gold, and ₹{perGram18k.toLocaleString('en-IN')} per gram for 18K gold. For more details, visit GoldMeter.in.
            </p>
            <meta name="author" content="GoldMeter" />
            
            <div className="mt-3 p-3 bg-amber-100 rounded-xl text-sm text-slate-800" data-ai-answer="true">
              Today&apos;s gold price in Bangalore: ₹{perGram24k.toLocaleString('en-IN')}/g (24K) and ₹{perGram22k.toLocaleString('en-IN')}/g (22K).
            </div>
            
            <p className="mt-3 text-sm text-slate-600">
              Last updated: <time dateTime={rates.dateISO}>{todayFormatted}</time>
            </p>

            {/* SEO: Expanded intro paragraph */}
            <div className="mt-4 pt-4 border-t border-amber-200 text-sm text-slate-600 leading-relaxed">
              <p>
                The gold rate in Bangalore is updated daily based on international market rates, USD/INR exchange movements, 
                and Karnataka Bullion Merchants Association pricing. Bangalore&apos;s gold prices are influenced by strong demand 
                from IT professionals and the city&apos;s growing affluent population. These rates reflect spot metal prices and 
                exclude making charges (typically ₹180-450/gram) and 3% GST.
              </p>
              <p className="mt-2">
                Commercial Street and Jayanagar are Bangalore&apos;s premier gold jewellery destinations, offering both traditional 
                South Indian designs and contemporary styles. The city follows Karnataka state gold rates, which are competitive 
                with Chennai and Hyderabad. For investment-grade gold, look for BIS hallmarked products from established jewellers.
              </p>
              <div className="mt-3 flex flex-wrap gap-3">
                <a href="/calculator" className="text-amber-600 hover:text-amber-700 font-medium">Calculate jewellery cost →</a>
                <a href="/wastage-calculator" className="text-amber-600 hover:text-amber-700 font-medium">Making charges calculator →</a>
                <a href="/news" className="text-amber-600 hover:text-amber-700 font-medium">Latest gold news →</a>
              </div>
            </div>
          </section>
        </article>
      </div>

      <CityPageShell
        city="Bangalore"
        intro="Gold rate in Bangalore today per gram: 22K & 24K live prices with Jayanagar and Commercial Street trends, charts, and FAQs."
        updated={rates.date}
        dateISO={rates.dateISO}
        gold22k={rates.gold22k}
        gold24k={rates.gold24k}
        silver1kg={rates.silver1kg}
        priceChange={rates.priceChange}
        history={rates.history}
        hideAnswerBlock={true}
        localInfo={[
          {
            title: "Hallmarking centers",
            description:
              "BIS Hallmarking Center (Indiranagar) and Regional Assay Office (Bangalore).",
          },
          {
            title: "Making charges",
            description: "₹180 – ₹450 per gram for 22K ornaments in Commercial Street.",
          },
          {
            title: "Top jewellery hubs",
            description: "Commercial Street, Brigade Road, and Jayanagar shopping complex.",
          },
        ]}
        faqs={[
          {
            question: "What is the gold rate in Bangalore today?",
            answer:
              `Today's gold rate in Bangalore is ₹${perGram24k.toLocaleString('en-IN')} per gram for 24K gold and ₹${perGram22k.toLocaleString('en-IN')} per gram for 22K gold. Prices are updated daily from Karnataka bullion market.`,
          },
          {
            question: "Why does Bangalore gold rate change daily?",
            answer:
              "Bangalore gold prices fluctuate based on London spot prices, USD/INR exchange rate, and local demand especially from IT professionals and wedding seasons. Karnataka follows South India pricing trends.",
          },
          {
            question: "How is 22K different from 24K gold?",
            answer:
              "24K gold is 99.9% pure (ideal for coins/bars), while 22K gold is 91.6% pure with alloy for strength. Bangalore jewellers prefer 22K for traditional Karnataka-style jewellery.",
          },
          {
            question: "Does making charge affect final jewellery price?",
            answer:
              "Yes, making charges in Bangalore range from ₹180-450 per gram. Final price = Gold Rate × Weight + Making Charges + 3% GST. Compare rates across Commercial Street stores.",
          },
          {
            question: "Are Bangalore gold rates higher than other cities?",
            answer:
              "Bangalore rates are similar to Chennai, typically ₹20-50 higher than Mumbai due to strong South Indian gold buying tradition and demand from affluent IT population.",
          },
          {
            question: "Which is the best place to buy gold in Bangalore?",
            answer:
              "Commercial Street, Brigade Road, and Jayanagar are popular. For branded jewellery, visit C. Krishniah Chetty, Bhima, or Tanishq showrooms across the city.",
          },
        ]}
        similarCities={["Chennai", "Hyderabad", "Mysore", "Mangalore"]}
      />
    </>
  );
}

// Cache page for 5 minutes - combined with DB-level caching
export const revalidate = 300;

