import { headers } from "next/headers";
import { Metadata } from "next";
import CityPageShell from "../components/CityPageShell";
import { fetchCityRates } from "@/lib/fetchCityRates";

// Dynamic metadata with date for AIO freshness signals
export async function generateMetadata(): Promise<Metadata> {
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
  
  return {
    title: `Mumbai Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices | GoldMeter`,
    description: `As of ${todayFormatted}, get today's Mumbai gold rate per gram for 22K and 24K gold. Compare prices, check making charges, and find best jewellery shops in Mumbai.`,
    alternates: {
      canonical: "https://goldmeter.in/mumbai",
    },
    openGraph: {
      title: `Mumbai Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices`,
      description: `As of ${todayFormatted}, get today's Mumbai gold rate per gram. Updated daily from Mumbai bullion market.`,
      type: 'website',
      url: 'https://goldmeter.in/mumbai',
    },
  };
}

export default async function MumbaiPage() {
  const headersList = await headers();
  const host = headersList.get("host") ?? "localhost:3000";
  
  const rates = await fetchCityRates("Mumbai", host);

  // Calculate per-gram prices for AIO answer block
  const perGram24k = Math.round((rates.gold24k || 0) / 10);
  const perGram22k = Math.round((rates.gold22k || 0) / 10);
  const perGram18k = Math.round(((rates.gold24k || 0) * 18) / 24 / 10);
  const silverPerGram = Math.round((rates.silver1kg || 0) / 1000);
  
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Note: Dataset schema is already generated by StructuredData component in CityPageShell
  // Do not add duplicate Dataset schema here to avoid Google Search Console errors

  return (
    <>
      {/* 🔥 AIO ANSWER BLOCK - Server-rendered plain HTML for AI scrapers */}
      <div className="bg-[#fffdf7]" itemScope itemType="https://schema.org/Product">
        <article className="mx-auto max-w-6xl px-4 pt-6">
          <section className="rounded-3xl border-2 border-amber-200 bg-gradient-to-r from-amber-50 to-white p-6 shadow-lg">
            <h1 className="text-2xl font-extrabold text-amber-800 md:text-3xl" itemProp="name">
              Mumbai Gold Rate Today ({todayFormatted})
            </h1>
            
            {/* Primary AIO answer - structured like competitors */}
            <p className="mt-3 text-base text-slate-700 leading-relaxed" data-ai-answer="true" itemProp="description">
              As of <time dateTime={rates.dateISO}>{todayFormatted}</time>, gold rates in Mumbai are <strong>₹{perGram24k.toLocaleString('en-IN')} per gram for 24K</strong> (99.9% purity), <strong>₹{perGram22k.toLocaleString('en-IN')} per gram for 22K</strong> (91.6% purity), and <strong>₹{perGram18k.toLocaleString('en-IN')} per gram for 18K</strong> (75.0% purity). Silver rate is ₹{silverPerGram.toLocaleString('en-IN')} per gram. For today&apos;s full gold rates, visit <strong>GoldMeter.in</strong>.
            </p>
            
            {/* Structured price table for AI extraction */}
            <div className="mt-4 overflow-x-auto" data-price-table="true">
              <table className="w-full text-sm border-collapse" itemProp="offers" itemScope itemType="https://schema.org/AggregateOffer">
                <caption className="text-left font-semibold text-amber-800 mb-2">
                  Today&apos;s Gold & Silver Rates in Mumbai
                  {/* Schema.org metadata for AggregateOffer - must be inside itemScope */}
                  <meta itemProp="priceCurrency" content="INR" />
                  <meta itemProp="lowPrice" content={perGram18k.toString()} />
                  <meta itemProp="highPrice" content={perGram24k.toString()} />
                </caption>
                <thead>
                  <tr className="bg-amber-100 text-amber-900">
                    <th className="px-3 py-2 text-left border border-amber-200">Metal</th>
                    <th className="px-3 py-2 text-left border border-amber-200">Purity</th>
                    <th className="px-3 py-2 text-left border border-amber-200">Rate per Gram</th>
                    <th className="px-3 py-2 text-left border border-amber-200">Rate per 10g</th>
                  </tr>
                </thead>
                <tbody className="text-slate-700">
                  <tr className="bg-white">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Gold 24K</td>
                    <td className="px-3 py-2 border border-amber-200">99.9%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{perGram24k.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{(rates.gold24k || 0).toLocaleString('en-IN')}</td>
                  </tr>
                  <tr className="bg-amber-50/50">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Gold 22K</td>
                    <td className="px-3 py-2 border border-amber-200">91.6%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{perGram22k.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{(rates.gold22k || 0).toLocaleString('en-IN')}</td>
                  </tr>
                  <tr className="bg-white">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Gold 18K</td>
                    <td className="px-3 py-2 border border-amber-200">75.0%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{perGram18k.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{(perGram18k * 10).toLocaleString('en-IN')}</td>
                  </tr>
                  <tr className="bg-slate-50">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Silver</td>
                    <td className="px-3 py-2 border border-amber-200">99.9%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{silverPerGram.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{Math.round((rates.silver1kg || 0) / 100).toLocaleString('en-IN')}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            
            <p className="mt-3 text-sm text-slate-600">
              Source: <strong>GoldMeter.in</strong> | Last updated: <time dateTime={rates.dateISO}>{todayFormatted}</time>
            </p>

            {/* SEO: Expanded intro paragraph */}
            <div className="mt-4 pt-4 border-t border-amber-200 text-sm text-slate-600 leading-relaxed">
              <p>
                The gold rate in Mumbai is updated daily based on international market rates, USD/INR currency movements, 
                and Zaveri Bazaar bullion market prices. Mumbai, being India&apos;s financial capital and home to MCX (Multi Commodity Exchange), 
                often sets the benchmark for gold prices across India. These rates reflect spot metal prices without making charges 
                (typically ₹200-500/gram in Zaveri Bazaar) or 3% GST.
              </p>
              <p className="mt-2">
                Zaveri Bazaar in South Mumbai is Asia&apos;s oldest and largest bullion market, dating back over 150 years. 
                Other popular jewellery destinations include Dadar, Borivali, and Malad. Mumbai&apos;s gold rates are typically 
                ₹20-50 lower than South Indian cities due to proximity to international trade routes and wholesale trading volumes.
              </p>
              <div className="mt-3 flex flex-wrap gap-3">
                <a href="/calculator" className="text-amber-600 hover:text-amber-700 font-medium">Calculate jewellery cost →</a>
                <a href="/wastage-calculator" className="text-amber-600 hover:text-amber-700 font-medium">Making charges calculator →</a>
                <a href="/news" className="text-amber-600 hover:text-amber-700 font-medium">Latest gold news →</a>
              </div>
            </div>
          </section>
        </article>
      </div>

      <CityPageShell
        city="Mumbai"
        intro="Gold rate in Mumbai today per gram: 22K & 24K live prices with Zaveri Bazaar and Dadar trends, charts, and FAQs."
        updated={rates.date}
        dateISO={rates.dateISO}
        gold22k={rates.gold22k}
        gold24k={rates.gold24k}
        silver1kg={rates.silver1kg}
        priceChange={rates.priceChange}
        history={rates.history}
        hideAnswerBlock={true}
        localInfo={[
          {
            title: "Hallmarking centers",
            description:
              "BIS Regional Office (Andheri) and Zaveri Bazaar Assay Office.",
          },
          {
            title: "Making charges",
            description: "₹200 – ₹500 per gram for 22K ornaments in Zaveri Bazaar.",
          },
          {
            title: "Top jewellery hubs",
            description: "Zaveri Bazaar, Dadar, and Andheri West flagship stores.",
          },
        ]}
        faqs={[
          {
            question: "What is the gold rate in Mumbai today?",
            answer:
              `Today's gold rate in Mumbai is ₹${perGram24k.toLocaleString('en-IN')} per gram for 24K gold and ₹${perGram22k.toLocaleString('en-IN')} per gram for 22K gold. Prices are updated daily from Zaveri Bazaar bullion market.`,
          },
          {
            question: "Why does Mumbai gold rate change daily?",
            answer:
              "Mumbai gold prices fluctuate based on London spot prices, MCX futures, USD/INR exchange rate, and trading volumes in Zaveri Bazaar. Being India's financial capital, Mumbai rates respond quickly to global market movements.",
          },
          {
            question: "How is 22K different from 24K gold?",
            answer:
              "24K gold is 99.9% pure (ideal for investment), while 22K gold is 91.6% pure with alloy metals for durability. Most Mumbai jewellers recommend 22K for ornaments and 24K for coins/bars.",
          },
          {
            question: "Does making charge affect final jewellery price?",
            answer:
              "Yes, making charges in Mumbai range from ₹200-500 per gram in Zaveri Bazaar. Final price = Gold Rate × Weight + Making Charges + 3% GST. Wholesale markets offer lower making charges.",
          },
          {
            question: "Are Mumbai gold rates lower than other cities?",
            answer:
              "Yes, Mumbai gold rates are typically ₹20-50 lower than Chennai or Bangalore due to proximity to ports, MCX trading, and higher wholesale volumes in Zaveri Bazaar.",
          },
          {
            question: "Which is the best place to buy gold in Mumbai?",
            answer:
              "Zaveri Bazaar (oldest bullion market), Dadar, Borivali, and Malad are popular. For branded jewellery, visit Tanishq, Kalyan, or PNG stores across the city.",
          },
        ]}
        similarCities={["Pune", "Ahmedabad", "Surat", "Chennai"]}
      />
    </>
  );
}

// Cache page for 5 minutes - combined with DB-level caching
export const revalidate = 300;

