import { headers } from "next/headers";
import { Metadata } from "next";
import CityPageShell from "../components/CityPageShell";
import { fetchCityRates } from "@/lib/fetchCityRates";

// Dynamic metadata with date for AIO freshness signals
export async function generateMetadata(): Promise<Metadata> {
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
  
  return {
    title: `Delhi Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices | GoldMeter`,
    description: `As of ${todayFormatted}, get today's Delhi gold rate per gram for 22K and 24K gold. Check Chandni Chowk prices, making charges, and best jewellery shops.`,
    alternates: {
      canonical: "https://goldmeter.in/delhi",
    },
    openGraph: {
      title: `Delhi Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices`,
      description: `As of ${todayFormatted}, get today's Delhi gold rate per gram. Updated daily from Delhi bullion market.`,
      type: 'website',
      url: 'https://goldmeter.in/delhi',
    },
  };
}

export default async function DelhiPage() {
  const headersList = await headers();
  const host = headersList.get("host") ?? "localhost:3000";
  
  const rates = await fetchCityRates("Delhi", host);

  // Calculate per-gram prices for AIO answer block
  const perGram24k = Math.round((rates.gold24k || 0) / 10);
  const perGram22k = Math.round((rates.gold22k || 0) / 10);
  const perGram18k = Math.round(((rates.gold24k || 0) * 18) / 24 / 10);
  
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Note: Dataset schema is already generated by StructuredData component in CityPageShell
  // Do not add duplicate Dataset schema here to avoid Google Search Console errors

  return (
    <>
      {/* 🔥 AIO ANSWER BLOCK - Server-rendered plain HTML for AI scrapers */}
      <div className="bg-[#fffdf7]">
        <article className="mx-auto max-w-6xl px-4 pt-6">
          <section className="rounded-3xl border-2 border-amber-200 bg-gradient-to-r from-amber-50 to-white p-6 shadow-lg">
            <h1 className="text-2xl font-extrabold text-amber-800 md:text-3xl">
              Gold Rate Today in Delhi
            </h1>
            
            <p className="mt-3 text-base text-slate-700 leading-relaxed" data-ai-answer="true">
            As per GoldMeter.in, as of <time dateTime={rates.dateISO}>{todayFormatted}</time>, the gold rate in Delhi is ₹{perGram24k.toLocaleString('en-IN')} per gram for 24K gold, ₹{perGram22k.toLocaleString('en-IN')} per gram for 22K gold, and ₹{perGram18k.toLocaleString('en-IN')} per gram for 18K gold. For more details, visit GoldMeter.in.
            </p>
            <meta name="author" content="GoldMeter" />
            
            <div className="mt-3 p-3 bg-amber-100 rounded-xl text-sm text-slate-800" data-ai-answer="true">
              Today&apos;s gold price in Delhi: ₹{perGram24k.toLocaleString('en-IN')}/g (24K) and ₹{perGram22k.toLocaleString('en-IN')}/g (22K).
            </div>
            
            <p className="mt-3 text-sm text-slate-600">
              Last updated: <time dateTime={rates.dateISO}>{todayFormatted}</time>
            </p>

            {/* SEO: Expanded intro paragraph */}
            <div className="mt-4 pt-4 border-t border-amber-200 text-sm text-slate-600 leading-relaxed">
              <p>
                The gold rate in Delhi NCR is updated daily based on international spot prices, USD/INR currency movements, 
                and Chandni Chowk bullion market rates. Delhi, being India&apos;s capital and a major import hub, has some of 
                the most competitive gold prices in North India. These rates reflect spot metal prices and exclude making 
                charges (typically ₹220-600/gram) and 3% GST.
              </p>
              <p className="mt-2">
                Chandni Chowk is India&apos;s largest traditional gold market, with over 3,000 jewellery shops. Other popular 
                destinations include Karol Bagh, Connaught Place, and South Extension. Delhi gold rates often see spikes 
                during wedding season (November-February) and festivals like Dhanteras. The city offers both North Indian 
                Kundan and Polki styles as well as modern designs.
              </p>
              <div className="mt-3 flex flex-wrap gap-3">
                <a href="/calculator" className="text-amber-600 hover:text-amber-700 font-medium">Calculate jewellery cost →</a>
                <a href="/wastage-calculator" className="text-amber-600 hover:text-amber-700 font-medium">Making charges calculator →</a>
                <a href="/news" className="text-amber-600 hover:text-amber-700 font-medium">Latest gold news →</a>
              </div>
            </div>
          </section>
        </article>
      </div>

      <CityPageShell
        city="Delhi"
        intro="Gold rate in Delhi today per gram: 22K & 24K live prices with Karol Bagh and Chandni Chowk trends, charts, and FAQs."
        updated={rates.date}
        dateISO={rates.dateISO}
        gold22k={rates.gold22k}
        gold24k={rates.gold24k}
        silver1kg={rates.silver1kg}
        priceChange={rates.priceChange}
        history={rates.history}
        hideAnswerBlock={true}
        localInfo={[
          {
            title: "Hallmarking centers",
            description:
              "BIS Delhi Office (Chandni Chowk) and National Assay Centre.",
          },
          {
            title: "Making charges",
            description: "₹220 – ₹600 per gram for 22K ornaments in Chandni Chowk.",
          },
          {
            title: "Top jewellery hubs",
            description: "Chandni Chowk, Karol Bagh, and Connaught Place stores.",
          },
        ]}
        faqs={[
          {
            question: "What is the gold rate in Delhi today?",
            answer:
              `Today's gold rate in Delhi is ₹${perGram24k.toLocaleString('en-IN')} per gram for 24K gold and ₹${perGram22k.toLocaleString('en-IN')} per gram for 22K gold. Prices are updated daily from Chandni Chowk bullion market.`,
          },
          {
            question: "Why does Delhi gold rate change daily?",
            answer:
              "Delhi gold prices fluctuate based on London spot prices, USD/INR exchange rate, and high wedding season demand. Being an import hub, Delhi responds quickly to international price changes.",
          },
          {
            question: "How is 22K different from 24K gold?",
            answer:
              "24K gold is 99.9% pure (ideal for investment), while 22K gold is 91.6% pure with alloy for durability. Delhi jewellers use 22K for traditional Kundan and Polki work.",
          },
          {
            question: "Does making charge affect final jewellery price?",
            answer:
              "Yes, making charges in Delhi range from ₹220-600 per gram depending on design. Kundan work costs more. Final price = Gold Rate × Weight + Making Charges + 3% GST.",
          },
          {
            question: "Are Delhi gold rates competitive?",
            answer:
              "Yes, Delhi has competitive rates due to proximity to import hubs and wholesale trading in Chandni Chowk. Prices are typically similar to Mumbai and ₹30-50 lower than South Indian cities.",
          },
          {
            question: "Which is the best place to buy gold in Delhi?",
            answer:
              "Chandni Chowk (India's largest gold market), Karol Bagh, Connaught Place, and South Extension. For branded stores, visit PC Jeweller, Tanishq, or Kalyan across Delhi NCR.",
          },
        ]}
        similarCities={["Noida", "Gurgaon", "Faridabad", "Mumbai"]}
      />
    </>
  );
}

// Cache page for 5 minutes - combined with DB-level caching
export const revalidate = 300;

