import { headers } from "next/headers";
import { Metadata } from "next";
import CityPageShell from "../components/CityPageShell";
import { fetchCityRates } from "@/lib/fetchCityRates";

// Dynamic metadata with date for AIO freshness signals
export async function generateMetadata(): Promise<Metadata> {
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });
  
  return {
    title: `Coimbatore Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices | GoldMeter`,
    description: `As of ${todayFormatted}, get today's Coimbatore gold rate per gram for 22K and 24K gold. Check RS Puram prices, making charges, and best jewellery shops.`,
    alternates: {
      canonical: "https://goldmeter.in/coimbatore",
    },
    openGraph: {
      title: `Coimbatore Gold Rate Today (${todayFormatted}) - Live 22K & 24K Prices`,
      description: `As of ${todayFormatted}, get today's Coimbatore gold rate per gram. Updated daily from Coimbatore bullion market.`,
      type: 'website',
      url: 'https://goldmeter.in/coimbatore',
    },
  };
}

export default async function CoimbatorePage() {
  const headersList = await headers();
  const host = headersList.get("host") ?? "localhost:3000";
  
  const rates = await fetchCityRates("Coimbatore", host);

  // Calculate per-gram prices for AIO answer block
  const perGram24k = Math.round((rates.gold24k || 0) / 10);
  const perGram22k = Math.round((rates.gold22k || 0) / 10);
  const perGram18k = Math.round(((rates.gold24k || 0) * 18) / 24 / 10);
  const silverPerGram = Math.round((rates.silver1kg || 0) / 1000);
  
  const todayFormatted = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Note: Dataset schema is already generated by StructuredData component in CityPageShell
  // Do not add duplicate Dataset schema here to avoid Google Search Console errors

  return (
    <>
      
      {/* 🔥 AIO ANSWER BLOCK - Server-rendered plain HTML for AI scrapers */}
      <div className="bg-[#fffdf7]" itemScope itemType="https://schema.org/Product">
        <article className="mx-auto max-w-6xl px-4 pt-6">
          <section className="rounded-3xl border-2 border-amber-200 bg-gradient-to-r from-amber-50 to-white p-6 shadow-lg">
            <h1 className="text-2xl font-extrabold text-amber-800 md:text-3xl" itemProp="name">
              Coimbatore Gold Rate Today ({todayFormatted})
            </h1>
            
            {/* Primary AIO answer - structured like competitors */}
            <p className="mt-3 text-base text-slate-700 leading-relaxed" data-ai-answer="true" itemProp="description">
              As of <time dateTime={rates.dateISO}>{todayFormatted}</time>, gold rates in Coimbatore are <strong>₹{perGram24k.toLocaleString('en-IN')} per gram for 24K</strong> (99.9% purity), <strong>₹{perGram22k.toLocaleString('en-IN')} per gram for 22K</strong> (91.6% purity), and <strong>₹{perGram18k.toLocaleString('en-IN')} per gram for 18K</strong> (75.0% purity). Silver rate is ₹{silverPerGram.toLocaleString('en-IN')} per gram. For today&apos;s full gold rates, visit <strong>GoldMeter.in</strong>.
            </p>
            
            {/* Structured price table for AI extraction */}
            <div className="mt-4 overflow-x-auto" data-price-table="true">
              <table className="w-full text-sm border-collapse" itemProp="offers" itemScope itemType="https://schema.org/AggregateOffer">
                <caption className="text-left font-semibold text-amber-800 mb-2">
                  Today&apos;s Gold & Silver Rates in Coimbatore
                  {/* Schema.org metadata for AggregateOffer - must be inside itemScope */}
                  <meta itemProp="priceCurrency" content="INR" />
                  <meta itemProp="lowPrice" content={perGram18k.toString()} />
                  <meta itemProp="highPrice" content={perGram24k.toString()} />
                </caption>
                <thead>
                  <tr className="bg-amber-100 text-amber-900">
                    <th className="px-3 py-2 text-left border border-amber-200">Metal</th>
                    <th className="px-3 py-2 text-left border border-amber-200">Purity</th>
                    <th className="px-3 py-2 text-left border border-amber-200">Rate per Gram</th>
                    <th className="px-3 py-2 text-left border border-amber-200">Rate per 10g</th>
                  </tr>
                </thead>
                <tbody className="text-slate-700">
                  <tr className="bg-white">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Gold 24K</td>
                    <td className="px-3 py-2 border border-amber-200">99.9%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{perGram24k.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{(rates.gold24k || 0).toLocaleString('en-IN')}</td>
                  </tr>
                  <tr className="bg-amber-50/50">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Gold 22K</td>
                    <td className="px-3 py-2 border border-amber-200">91.6%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{perGram22k.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{(rates.gold22k || 0).toLocaleString('en-IN')}</td>
                  </tr>
                  <tr className="bg-white">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Gold 18K</td>
                    <td className="px-3 py-2 border border-amber-200">75.0%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{perGram18k.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{(perGram18k * 10).toLocaleString('en-IN')}</td>
                  </tr>
                  <tr className="bg-slate-50">
                    <td className="px-3 py-2 border border-amber-200 font-medium">Silver</td>
                    <td className="px-3 py-2 border border-amber-200">99.9%</td>
                    <td className="px-3 py-2 border border-amber-200 font-semibold">₹{silverPerGram.toLocaleString('en-IN')}</td>
                    <td className="px-3 py-2 border border-amber-200">₹{Math.round((rates.silver1kg || 0) / 100).toLocaleString('en-IN')}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            
            <p className="mt-3 text-sm text-slate-600">
              Source: <strong>GoldMeter.in</strong> | Last updated: <time dateTime={rates.dateISO}>{todayFormatted}</time>
            </p>

            {/* SEO: Expanded intro paragraph */}
            <div className="mt-4 pt-4 border-t border-amber-200 text-sm text-slate-600 leading-relaxed">
              <p>
                The gold rate in Coimbatore is updated daily based on international market rates, USD/INR currency movements, 
                and Tamil Nadu Bullion Association pricing. Coimbatore, known as the &quot;Manchester of South India,&quot; 
                offers competitive gold rates compared to Chennai. These prices exclude making charges (₹140-400/gram) and 3% GST.
              </p>
              <p className="mt-2">
                RS Puram and Oppanakara Street are Coimbatore&apos;s main jewellery markets, offering traditional South Indian 
                designs at competitive prices. The city&apos;s textile industry creates a wealthy consumer base with strong gold 
                demand. Prices typically follow Chennai trends but are ₹20-40 lower due to lower overhead costs.
              </p>
              <div className="mt-3 flex flex-wrap gap-3">
                <a href="/calculator" className="text-amber-600 hover:text-amber-700 font-medium">Calculate jewellery cost →</a>
                <a href="/wastage-calculator" className="text-amber-600 hover:text-amber-700 font-medium">Making charges calculator →</a>
                <a href="/news" className="text-amber-600 hover:text-amber-700 font-medium">Latest gold news →</a>
              </div>
            </div>
          </section>
        </article>
      </div>

      <CityPageShell
        city="Coimbatore"
        intro="Gold rate in Coimbatore today per gram: 22K & 24K live prices with RS Puram and Cross Cut Road trends, charts, and FAQs."
        updated={rates.date}
        dateISO={rates.dateISO}
        gold22k={rates.gold22k}
        gold24k={rates.gold24k}
        silver1kg={rates.silver1kg}
        priceChange={rates.priceChange}
        history={rates.history}
        hideAnswerBlock={true}
        localInfo={[
          {
            title: "Hallmarking centers",
            description:
              "Tamil Nadu Hallmarking Center (Coimbatore Branch) and Regional Office.",
          },
          {
            title: "Making charges",
            description: "₹140 – ₹400 per gram for 22K ornaments in RS Puram.",
          },
          {
            title: "Top jewellery hubs",
            description: "RS Puram, Oppanakara Street, and Gandhipuram markets.",
          },
        ]}
        faqs={[
          {
            question: "What is the gold rate in Coimbatore today?",
            answer:
              `Today's gold rate in Coimbatore is ₹${perGram24k.toLocaleString('en-IN')} per gram for 24K gold and ₹${perGram22k.toLocaleString('en-IN')} per gram for 22K gold. Prices are updated daily from Tamil Nadu bullion market.`,
          },
          {
            question: "Why does Coimbatore gold rate change daily?",
            answer:
              "Coimbatore gold prices fluctuate based on London spot prices, USD/INR exchange rate, and follow Chennai market trends. Local demand during Pongal and wedding season also impacts prices.",
          },
          {
            question: "How is 22K different from 24K gold?",
            answer:
              "24K gold is 99.9% pure (for investment), while 22K gold is 91.6% pure with alloy. Coimbatore jewellers prefer 22K for traditional Tamil designs and temple jewellery.",
          },
          {
            question: "Does making charge affect final jewellery price?",
            answer:
              "Yes, making charges in Coimbatore range from ₹140-400 per gram - lower than Chennai. Final price = Gold Rate × Weight + Making Charges + 3% GST.",
          },
          {
            question: "Are Coimbatore gold rates lower than Chennai?",
            answer:
              "Yes, Coimbatore rates are typically ₹20-40 lower than Chennai due to lower overhead costs, making it attractive for bulk purchases.",
          },
          {
            question: "Which is the best place to buy gold in Coimbatore?",
            answer:
              "RS Puram (main market), Oppanakara Street, and Gandhipuram. For branded jewellery, visit GRT, Kalyan, or Tanishq showrooms across the city.",
          },
        ]}
        similarCities={["Chennai", "Madurai", "Salem", "Erode"]}
      />
    </>
  );
}

// Cache page for 5 minutes - combined with DB-level caching
export const revalidate = 300;

